name: Kosmos
version: ${pom.version}-BUKKIT+${describe}
author: Cory Redmond
main: com.minecraftly.bukkit.MinecraftlyBukkitPlugin
description: Kosmos cloud platform
load: STARTUP
website: http://minecraftly.com/
commands:
  mdebug:
    description: A debugging command
    aliases: [mdebug]
  list:
    description: Get a list of currently online players in the current world
  world:
    description: Go to the specified world
  spawn:
    description: Teleport to the spawn of the current world
  setspawn:
    description: Set the spawn of the current world
  home:
    description: Teleport to the spawn of the current world
  sethome:
    description: Set a home
  delhome:
    description: Delete the specified home
  whitelist:
    description: The base whitelist command
  trust:
    description: Allows the specified player to build
  untrust:
    description: Disallows the specified player to build
  trusted:
    description: Get a list of currently trusted online players
  ban:
    description: Prevents the specified player joining
  unban:
    description: Allows the specified player to join
  kick:
    description: Kicks the specified player
  mute:
    description: Prevents the specified player from speaking
  unmute:
    description: Allows the specified player to chat
  muted:
    description: Get a list of currently muted online players
  shout:
    description: Shout globally
    aliases: [y, yell]
